# fly.toml configuration file for clip-backend
# Generated for Fly.io deployment
# See: https://fly.io/docs/v2/app-configuration/ for details

app = "fly-app"
primary_region = "iad"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/pnpm"]

[env]
  NODE_ENV = "production"
  PORT = "8086"
  API_BASE_URL = "https://clip-backend-f93c.onrender.com"
  AWS_ENDPOINT_URL_S3 = "https://fly.storage.tigris.dev"
  AWS_REGION = "auto"
  BUCKET_NAME = "clip-backend-bucket"

[http_service]
  internal_port = 8086
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[services]]
  internal_port = 8086
  protocol = "tcp"
  processes = ["app"]

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"

[metrics]
  port = 9091
  path = "/metrics"

[deploy]
  release_command = "node_modules/.bin/knex migrate:latest"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"